import React, { useState } from 'react';
import { UserPreferences } from '../../scanner/types';
import { PreferenceStorage } from '../../lib/storage';

interface SettingsViewProps {
  preferences: UserPreferences;
  onPreferencesChange: (newPrefs: UserPreferences) => void;
}

export const SettingsView: React.FC<SettingsViewProps> = ({ preferences, onPreferencesChange }) => {
  const [newDomain, setNewDomain] = useState<string>('');
  const [statusMessage, setStatusMessage] = useState<string | null>(null);

  const handleGradeChange = (grade: 6 | 8) => {
    const updated: UserPreferences = { ...preferences, cognitiveReadingGrade: grade };
    onPreferencesChange(updated);
    PreferenceStorage.savePreferences(updated);
    showNotice(`Explanation complexity set to Grade ${grade}.`);
  };

  const handleWorkerToggle = () => {
    const updated: UserPreferences = {
      ...preferences,
      enableWorkerOffloading: !preferences.enableWorkerOffloading
    };
    onPreferencesChange(updated);
    PreferenceStorage.savePreferences(updated);
    showNotice(
      updated.enableWorkerOffloading
        ? 'Web Worker background offloading enabled.'
        : 'Main thread direct scanning enabled.'
    );
  };

  const handleAddDomain = (e: React.FormEvent) => {
    e.preventDefault();
    const clean = newDomain.trim().toLowerCase();
    if (!clean || preferences.allowlistDomains.includes(clean)) return;

    const updated: UserPreferences = {
      ...preferences,
      allowlistDomains: [...preferences.allowlistDomains, clean]
    };
    onPreferencesChange(updated);
    PreferenceStorage.savePreferences(updated);
    setNewDomain('');
    showNotice(`Added '${clean}' to local allowlist.`);
  };

  const handleRemoveDomain = (domainToRemove: string) => {
    const updated: UserPreferences = {
      ...preferences,
      allowlistDomains: preferences.allowlistDomains.filter((d) => d !== domainToRemove)
    };
    onPreferencesChange(updated);
    PreferenceStorage.savePreferences(updated);
    showNotice(`Removed '${domainToRemove}' from local allowlist.`);
  };

  const handleClearAll = () => {
    PreferenceStorage.clearAllData();
    const resetPrefs: UserPreferences = {
      cognitiveReadingGrade: 6,
      enableWorkerOffloading: true,
      allowlistDomains: []
    };
    onPreferencesChange(resetPrefs);
    showNotice('All local preferences cleared and reset to defaults.');
  };

  const showNotice = (msg: string) => {
    setStatusMessage(msg);
    setTimeout(() => setStatusMessage(null), 3000);
  };

  return (
    <section aria-labelledby="settings-heading" style={{ maxWidth: '800px', margin: '0 auto' }}>
      <div style={{ marginBottom: '1.5rem' }}>
        <h2 id="settings-heading" style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: '0.5rem' }}>
          Dashboard Settings & Preferences
        </h2>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>
          Customize on-device scanner behavior, reading levels, and local allowlists.
          All settings reside in browser storage and are never uploaded.
        </p>
      </div>

      {statusMessage && (
        <div
          role="status"
          style={{
            padding: '0.65rem 1rem',
            backgroundColor: 'rgba(59, 130, 246, 0.1)',
            border: '1px solid #3b82f6',
            borderRadius: '0.375rem',
            color: '#93c5fd',
            fontSize: '0.85rem',
            marginBottom: '1rem'
          }}
        >
          {statusMessage}
        </div>
      )}

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
        {/* 1. Cognitive Reading Grade Level */}
        <div
          style={{
            padding: '1.25rem',
            backgroundColor: 'var(--bg-card)',
            border: '1px solid var(--border-color)',
            borderRadius: '0.5rem'
          }}
        >
          <h3 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '0.35rem' }}>
            Explanation Reading Level
          </h3>
          <p style={{ fontSize: '0.825rem', color: 'var(--text-muted)', marginBottom: '0.75rem' }}>
            Select the cognitive complexity for threat explanations generated by the AI Security Assistant.
          </p>

          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button
              type="button"
              onClick={() => handleGradeChange(6)}
              style={{
                padding: '0.5rem 1rem',
                backgroundColor: preferences.cognitiveReadingGrade === 6 ? 'var(--color-brand)' : 'var(--bg-secondary)',
                color: preferences.cognitiveReadingGrade === 6 ? '#ffffff' : 'var(--text-primary)',
                border: '1px solid var(--border-color)',
                borderRadius: '0.375rem',
                fontSize: '0.85rem',
                fontWeight: 600,
                cursor: 'pointer'
              }}
            >
              Grade 6 (Plain Language, Recommended)
            </button>
            <button
              type="button"
              onClick={() => handleGradeChange(8)}
              style={{
                padding: '0.5rem 1rem',
                backgroundColor: preferences.cognitiveReadingGrade === 8 ? 'var(--color-brand)' : 'var(--bg-secondary)',
                color: preferences.cognitiveReadingGrade === 8 ? '#ffffff' : 'var(--text-primary)',
                border: '1px solid var(--border-color)',
                borderRadius: '0.375rem',
                fontSize: '0.85rem',
                fontWeight: 600,
                cursor: 'pointer'
              }}
            >
              Grade 8 (Standard Technical Detail)
            </button>
          </div>
        </div>

        {/* 2. Web Worker Execution */}
        <div
          style={{
            padding: '1.25rem',
            backgroundColor: 'var(--bg-card)',
            border: '1px solid var(--border-color)',
            borderRadius: '0.5rem'
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <h3 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '0.35rem' }}>
                Web Worker Background Processing
              </h3>
              <p style={{ fontSize: '0.825rem', color: 'var(--text-muted)' }}>
                Offloads entropy calculations and token parsing to an isolated background thread.
              </p>
            </div>
            <button
              type="button"
              onClick={handleWorkerToggle}
              style={{
                padding: '0.5rem 1rem',
                backgroundColor: preferences.enableWorkerOffloading ? '#065f46' : 'var(--bg-secondary)',
                color: preferences.enableWorkerOffloading ? '#6ee7b7' : 'var(--text-muted)',
                border: '1px solid var(--border-color)',
                borderRadius: '0.375rem',
                fontSize: '0.85rem',
                fontWeight: 600,
                cursor: 'pointer'
              }}
            >
              {preferences.enableWorkerOffloading ? 'Enabled (Smooth 60fps)' : 'Disabled (Main Thread)'}
            </button>
          </div>
        </div>

        {/* 3. Custom Local Allowlist */}
        <div
          style={{
            padding: '1.25rem',
            backgroundColor: 'var(--bg-card)',
            border: '1px solid var(--border-color)',
            borderRadius: '0.5rem'
          }}
        >
          <h3 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '0.35rem' }}>
            Custom Local Allowlists
          </h3>
          <p style={{ fontSize: '0.825rem', color: 'var(--text-muted)', marginBottom: '0.75rem' }}>
            Specify trusted internal domains or intranet addresses that should always be allowed.
          </p>

          <form onSubmit={handleAddDomain} style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.75rem' }}>
            <input
              type="text"
              placeholder="e.g. internal.corp.local"
              value={newDomain}
              onChange={(e) => setNewDomain(e.target.value)}
              style={{
                flex: 1,
                padding: '0.5rem 0.75rem',
                backgroundColor: 'var(--bg-secondary)',
                border: '1px solid var(--border-color)',
                borderRadius: '0.375rem',
                color: 'var(--text-primary)',
                fontSize: '0.85rem'
              }}
            />
            <button
              type="submit"
              disabled={!newDomain.trim()}
              style={{
                padding: '0.5rem 1rem',
                backgroundColor: 'var(--color-brand)',
                color: '#ffffff',
                border: 'none',
                borderRadius: '0.375rem',
                fontSize: '0.85rem',
                fontWeight: 600,
                cursor: !newDomain.trim() ? 'not-allowed' : 'pointer'
              }}
            >
              Add Domain
            </button>
          </form>

          {preferences.allowlistDomains.length > 0 ? (
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
              {preferences.allowlistDomains.map((d) => (
                <span
                  key={d}
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '0.35rem',
                    padding: '0.25rem 0.6rem',
                    backgroundColor: 'rgba(59, 130, 246, 0.1)',
                    border: '1px solid rgba(59, 130, 246, 0.3)',
                    borderRadius: '0.25rem',
                    fontSize: '0.8rem',
                    color: '#93c5fd'
                  }}
                >
                  {d}
                  <button
                    type="button"
                    aria-label={`Remove ${d}`}
                    onClick={() => handleRemoveDomain(d)}
                    style={{
                      background: 'none',
                      border: 'none',
                      color: '#f87171',
                      cursor: 'pointer',
                      fontSize: '0.85rem'
                    }}
                  >
                    ×
                  </button>
                </span>
              ))}
            </div>
          ) : (
            <span style={{ fontSize: '0.8rem', color: '#64748b' }}>No custom allowlisted domains configured.</span>
          )}
        </div>

        {/* 4. Crypto-Shred & Reset */}
        <div
          style={{
            padding: '1.25rem',
            backgroundColor: 'var(--bg-card)',
            border: '1px solid var(--border-color)',
            borderRadius: '0.5rem',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            flexWrap: 'wrap',
            gap: '1rem'
          }}
        >
          <div>
            <h3 style={{ fontSize: '1rem', fontWeight: 600, color: '#f87171', marginBottom: '0.25rem' }}>
              Clear Local Client State
            </h3>
            <p style={{ fontSize: '0.825rem', color: 'var(--text-muted)' }}>
              Crypto-shreds and wipes all local browser settings.
            </p>
          </div>
          <button
            type="button"
            onClick={handleClearAll}
            style={{
              padding: '0.5rem 1rem',
              backgroundColor: 'rgba(239, 68, 68, 0.1)',
              border: '1px solid #ef4444',
              color: '#fca5a5',
              borderRadius: '0.375rem',
              fontSize: '0.85rem',
              fontWeight: 600,
              cursor: 'pointer'
            }}
          >
            Clear All Local Data
          </button>
        </div>
      </div>
    </section>
  );
};
