import {
  InferenceRequest,
  InferenceResult,
  ModelMetadata,
  ScamIntent
} from '../../types';
import { BaseModelProvider } from './model-provider';

/**
 * DEVELOPMENT AND TEST HARNESS MODEL PROVIDER
 *
 * IMPORTANT GOVERNANCE NOTICE:
 * This class is explicitly a development fixture and test mock provider.
 * It is NEVER a production model and MUST NOT be presented as a trained neural network.
 * It exists to verify provider abstraction lifecycles, tensor interfaces,
 * timeout handling, and deterministic fallback mechanics in automated unit tests.
 */
export class DevelopmentMockModelProvider extends BaseModelProvider {
  public readonly id = 'dev-mock-intent-classifier-v1';
  public readonly metadata: ModelMetadata = {
    modelId: 'dev-mock-intent-classifier-v1',
    version: '0.1.0-test-fixture',
    format: 'ONNX',
    task: 'INTENT_CLASSIFICATION',
    sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', // Empty SHA fixture
    sizeBytes: 1024,
    inputShape: [1, 128],
    outputClasses: [
      ScamIntent.PHISHING_CREDENTIALS,
      ScamIntent.URGENCY_EXTORTION,
      ScamIntent.ADVANCE_FEE_FRAUD,
      ScamIntent.EMPLOYMENT_TASK_SCAM,
      ScamIntent.TECH_SUPPORT_INVOICE,
      ScamIntent.POSTAL_DELIVERY_FRAUD,
      ScamIntent.BENIGN_COMMUNICATION
    ],
    quantization: 'INT8',
    isProductionArtifact: false,
    providerName: 'DevelopmentMockProvider',
    description: 'Explicit development and test mock provider for harness verification'
  };

  private simulatedLatencyMs: number;
  private failLoad: boolean;

  constructor(options?: { simulatedLatencyMs?: number; failLoad?: boolean }) {
    super();
    this.simulatedLatencyMs = options?.simulatedLatencyMs ?? 5;
    this.failLoad = options?.failLoad ?? false;
  }

  public async load(): Promise<boolean> {
    if (this.failLoad) {
      this.loaded = false;
      return false;
    }
    this.loaded = true;
    return true;
  }

  public async infer(request: InferenceRequest): Promise<InferenceResult> {
    const startTime = Date.now();

    if (!this.loaded) {
      return {
        requestId: request.requestId,
        predictions: {},
        topLabel: 'UNLOADED',
        topScore: 0.0,
        confidence: 0.0,
        uncertainty: 1.0,
        latencyMs: 0,
        status: 'FALLBACK',
        modelMetadata: this.metadata,
        error: 'ModelNotLoadedError: provider must be loaded before running inference'
      };
    }

    if (this.simulatedLatencyMs > 0) {
      await new Promise(resolve => setTimeout(resolve, this.simulatedLatencyMs));
    }

    // Input validation
    const inputStr = typeof request.input === 'string'
      ? request.input
      : JSON.stringify(request.input);

    const latencyMs = Math.max(0.1, Date.now() - startTime);

    if (request.task === 'EXPLANATION_SYNTHESIS') {
      const mockOutput = {
        headline: 'Warning: Deceptive Web Target',
        summaryParagraph: 'This website appears designed to trick users into revealing confidential security information.',
        dangerFactors: [
          'Deceptive website address format.',
          'Attempts to harvest user credentials.'
        ],
        recommendedSteps: [
          'Do not submit sensitive credentials.',
          'Close the browser tab immediately.'
        ],
        uncertaintyNote: 'Generated by local test harness model provider.'
      };

      return {
        requestId: request.requestId,
        predictions: { EXPLANATION_SYNTHESIS: 0.90 },
        rawOutput: mockOutput,
        topLabel: 'EXPLANATION_SYNTHESIS',
        topScore: 0.90,
        confidence: 0.85,
        uncertainty: 0.15,
        latencyMs,
        status: 'SUCCESS',
        modelMetadata: this.metadata
      };
    }

    // Standard uniform prior with mild ambiguity scores for test harness verification
    const predictions: Record<string, number> = {
      [ScamIntent.PHISHING_CREDENTIALS]: 0.15,
      [ScamIntent.URGENCY_EXTORTION]: 0.15,
      [ScamIntent.ADVANCE_FEE_FRAUD]: 0.10,
      [ScamIntent.EMPLOYMENT_TASK_SCAM]: 0.15,
      [ScamIntent.TECH_SUPPORT_INVOICE]: 0.15,
      [ScamIntent.POSTAL_DELIVERY_FRAUD]: 0.10,
      [ScamIntent.BENIGN_COMMUNICATION]: 0.20
    };

    return {
      requestId: request.requestId,
      predictions,
      topLabel: ScamIntent.BENIGN_COMMUNICATION,
      topScore: 0.20,
      confidence: 0.35, // Low confidence reflecting mock nature
      uncertainty: 0.65,
      latencyMs,
      status: 'UNCERTAIN',
      modelMetadata: this.metadata
    };
  }
}
